puts "The potential names of my fellow students ha"
puts "--------------------------------------"
puts "Toby Lerone"
puts "Mal Teaser"
puts "Anette Kurtain"
puts "Zultan Pepper"
puts "Chris Peacock"
puts "Chris P Bird"
puts "Liz Anier"
puts "Karl Hickbread"
puts "Mark N Spencer"